runtime: python37
env: standard

runtime_config:
  python_version: 3

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /dist
  static_dir: dist
- url: .*
  secure: always
  static_dir: auto
